# Generated by Django 6.0.6 on 2026-06-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_categoria_cliente_proveedor_alter_movimiento_tipo_and_more'),
    ]

    operations = [
    ]
